# Generated by Django 4.0.4 on 2022-04-26 11:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HairColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Цвет волос')),
            ],
            options={
                'verbose_name': 'Цвет волос',
                'verbose_name_plural': 'Цвет волос',
            },
        ),
        migrations.CreateModel(
            name='Girls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('growth', models.PositiveBigIntegerField(verbose_name='Рост')),
                ('weight', models.DecimalField(decimal_places=0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Вес')),
                ('girls_description', models.CharField(max_length=300, unique=True, verbose_name='Краткое описание')),
                ('phone', models.PositiveIntegerField(default=88002000500, verbose_name='Контактный телефон')),
                ('listing_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в базу')),
                ('update_list_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('married', 'Замужем'), ('unmarried', 'Незамужняя')], default='unmarried', max_length=25, verbose_name='Статус')),
                ('hair_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trenia_telki.haircolor', verbose_name='Цвет волос')),
            ],
            options={
                'verbose_name': 'Девушка',
                'verbose_name_plural': 'Девушки',
            },
        ),
    ]
